version: '3'

services:
  app:
    build: .
    container_name: micro-videos-typescript-app
    volumes:
      - .:/home/node/app

# linha 7: pega tudo que tรก no projeto (.:) e manda para "/home/node/app"